### ISSUE TITLE
shopify populate products didn't worked

### ISSUE THREAD

**Issue by ivorpad** [Shopify/shopify-app-cli#792]
I tried running this command after successfully running `shopify connect` with a Rails app and this is the stacktrace:

```bash
» → shopify populate products
This command ran with ID: 00052
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	26: from /usr/local/Cellar/shopify-cli/1.0.2/src/bin/shopify:30:in `<main>'
	25: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	24: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	23: from /usr/local/Cellar/shopify-cli/1.0.2/src/bin/shopify:31:in `block in <main>'
	22: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/entry_point.rb:39:in `call'
	21: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/monorail.rb:20:in `log'
	20: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/entry_point.rb:40:in `block in call'
	19: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/executor.rb:17:in `call'
	18: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	17: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	16: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	15: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	14: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	13: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	12: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	11: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	10: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-ui/lib/cli/ui.rb:171:in `log_output_to'
	 9: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	 8: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	 7: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	 6: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	 5: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/command.rb:17:in `call'
	 4: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/admin_api/populate_resource_command.rb:17:in `call'
	 3: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/admin_api/populate_resource_command.rb:34:in `call'
	 2: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/admin_api/populate_resource_command.rb:103:in `input_options'
	 1: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/admin_api/populate_resource_command.rb:114:in `schema'
/usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/admin_api/schema.rb:8:in `get': undefined method `get_shop' for ShopifyCli::AdminAPI::Schema:Class (NoMethodError)
```

**Comment by andyw8** [comment]
Hi @ivorpad 

Thanks for the detailed report – it looks like a bug was recently introduced in #760. We're working to fix that.

In the meantime, you should be able to work around this by providing your shop name as an environment variable, e.g.:

`SHOP=ivorpad-store.myshopify.com shopify populate products`

(where `ivorpad-store` is replaced with your actual store name)

**Comment by andyw8** [comment]
(If the above doesn't work, you may need to add the `SHOP=ivorpad-store.myshopify.com` line to your `.env` config file).

**Comment by andyw8** [comment]
Version 1.0.3 has been released with a fix for this.
